FROM tensorflow/tensorflow:2.4.1-gpu

RUN apt update && apt install -y \
        wget \
        git \
        git-lfs && \
    apt clean

RUN python3 -m pip install --upgrade pip
COPY requirements.txt /env/requirements.txt
RUN python3 -m pip install --no-cache-dir -r /env/requirements.txt

COPY entrypoint.sh /env/entrypoint.sh
RUN chmod +x /env/entrypoint.sh

ENTRYPOINT [ "/env/entrypoint.sh" ]
